comment servo func calls from main b/c errors when not connected
a lot of errors, NEED to handle gracefully:
(.venv) team14@pi:~/BWC-Vision-Testing-System $ python3 -m src.main
--- Starting BWC Water Heater Vision Testing System ---
[INFO] Test report CSV: /home/team14/BWC-Vision-Testing-System/data/test_reports/20260604_113355_890268_test_report.csv
[INFO] Cleaning up old captures.
[INFO] Capture cleanup applied (retention=14 days).
[INFO] Initializing servos.

[EMERGENCY] Unhandled exception caught!
Traceback (most recent call last):
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 168, in __probe_for_device
    self.i2c.writeto(self.device_address, b"")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/src/motion/servo_driver.py", line 61, in writeto
    return self._i2c.writeto(
           ~~~~~~~~~~~~~~~~~^
        address,
        ^^^^^^^^
    ...<3 lines>...
        stop=stop,
        ^^^^^^^^^^
    )
    ^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 68, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/Adafruit_PureIO/smbus.py", line 303, in write_bytes
    self._device.write(buf)
    ~~~~~~~~~~~~~~~~~~^^^^^
OSError: [Errno 6] No such device or address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 174, in __probe_for_device
    self.i2c.readfrom_into(self.device_address, result)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/src/motion/servo_driver.py", line 70, in readfrom_into
    return self._i2c.readfrom_into(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        address,
        ^^^^^^^^
    ...<3 lines>...
        stop=stop,
        ^^^^^^^^^^
    )
    ^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 75, in readfrom_into
    readin = self._i2c_bus.read_bytes(address, end - start)
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/Adafruit_PureIO/smbus.py", line 170, in read_bytes
    return self._device.read(number)
           ~~~~~~~~~~~~~~~~~^^^^^^^^
OSError: [Errno 6] No such device or address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/team14/BWC-Vision-Testing-System/src/main.py", line 77, in main
    servo_driver.initialize()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/team14/BWC-Vision-Testing-System/src/motion/servo_driver.py", line 119, in initialize
    _kit = ServoKit(
        channels=16,
        i2c=i2c,
    )
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_servokit.py", line 90, in __init__
    self._pca = PCA9685(i2c, address=address, reference_clock_speed=reference_clock_speed)
                ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_pca9685.py", line 151, in __init__
    self.i2c_device = i2c_device.I2CDevice(i2c_bus, address)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 62, in __init__
    self.__probe_for_device()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 176, in __probe_for_device
    raise ValueError(f"No I2C device at address: 0x{self.device_address:x}")
ValueError: No I2C device at address: 0x40
Traceback (most recent call last):
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 168, in __probe_for_device
    self.i2c.writeto(self.device_address, b"")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/src/motion/servo_driver.py", line 61, in writeto
    return self._i2c.writeto(
           ~~~~~~~~~~~~~~~~~^
        address,
        ^^^^^^^^
    ...<3 lines>...
        stop=stop,
        ^^^^^^^^^^
    )
    ^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 68, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/Adafruit_PureIO/smbus.py", line 303, in write_bytes
    self._device.write(buf)
    ~~~~~~~~~~~~~~~~~~^^^^^
OSError: [Errno 6] No such device or address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 174, in __probe_for_device
    self.i2c.readfrom_into(self.device_address, result)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/src/motion/servo_driver.py", line 70, in readfrom_into
    return self._i2c.readfrom_into(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        address,
        ^^^^^^^^
    ...<3 lines>...
        stop=stop,
        ^^^^^^^^^^
    )
    ^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 75, in readfrom_into
    readin = self._i2c_bus.read_bytes(address, end - start)
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/Adafruit_PureIO/smbus.py", line 170, in read_bytes
    return self._device.read(number)
           ~~~~~~~~~~~~~~~~~^^^^^^^^
OSError: [Errno 6] No such device or address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/team14/BWC-Vision-Testing-System/src/main.py", line 77, in main
    servo_driver.initialize()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/team14/BWC-Vision-Testing-System/src/motion/servo_driver.py", line 119, in initialize
    _kit = ServoKit(
        channels=16,
        i2c=i2c,
    )
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_servokit.py", line 90, in __init__
    self._pca = PCA9685(i2c, address=address, reference_clock_speed=reference_clock_speed)
                ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_pca9685.py", line 151, in __init__
    self.i2c_device = i2c_device.I2CDevice(i2c_bus, address)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 62, in __init__
    self.__probe_for_device()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 176, in __probe_for_device
    raise ValueError(f"No I2C device at address: 0x{self.device_address:x}")
ValueError: No I2C device at address: 0x40

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 168, in __probe_for_device
    self.i2c.writeto(self.device_address, b"")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/src/motion/servo_driver.py", line 61, in writeto
    return self._i2c.writeto(
           ~~~~~~~~~~~~~~~~~^
        address,
        ^^^^^^^^
    ...<3 lines>...
        stop=stop,
        ^^^^^^^^^^
    )
    ^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 68, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/Adafruit_PureIO/smbus.py", line 303, in write_bytes
    self._device.write(buf)
    ~~~~~~~~~~~~~~~~~~^^^^^
OSError: [Errno 6] No such device or address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 174, in __probe_for_device
    self.i2c.readfrom_into(self.device_address, result)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/src/motion/servo_driver.py", line 70, in readfrom_into
    return self._i2c.readfrom_into(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        address,
        ^^^^^^^^
    ...<3 lines>...
        stop=stop,
        ^^^^^^^^^^
    )
    ^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 75, in readfrom_into
    readin = self._i2c_bus.read_bytes(address, end - start)
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/Adafruit_PureIO/smbus.py", line 170, in read_bytes
    return self._device.read(number)
           ~~~~~~~~~~~~~~~~~^^^^^^^^
OSError: [Errno 6] No such device or address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/team14/BWC-Vision-Testing-System/src/main.py", line 197, in <module>
    main()
    ~~~~^^
  File "/home/team14/BWC-Vision-Testing-System/src/main.py", line 190, in main
    servo_driver.home_all()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/team14/BWC-Vision-Testing-System/src/motion/servo_driver.py", line 142, in home_all
    initialize()
    ~~~~~~~~~~^^
  File "/home/team14/BWC-Vision-Testing-System/src/motion/servo_driver.py", line 119, in initialize
    _kit = ServoKit(
        channels=16,
        i2c=i2c,
    )
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_servokit.py", line 90, in __init__
    self._pca = PCA9685(i2c, address=address, reference_clock_speed=reference_clock_speed)
                ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_pca9685.py", line 151, in __init__
    self.i2c_device = i2c_device.I2CDevice(i2c_bus, address)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 62, in __init__
    self.__probe_for_device()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/team14/BWC-Vision-Testing-System/.venv/lib/python3.13/site-packages/adafruit_bus_device/i2c_device.py", line 176, in __probe_for_device
    raise ValueError(f"No I2C device at address: 0x{self.device_address:x}")
ValueError: No I2C device at address: 0x40